### ISSUE TITLE
Getting 'TypeError: Cannot set property 'clearInputs' of undefined' trying to use as library

### ISSUE THREAD

**Issue by wpride** [enketo/enketo-core#324]
TypeError: Cannot set property 'clearInputs' of undefined
    at [project_path]/node_modules/enketo-core/src/js/plugins.js:18:22
    at define ([project_path]/node_modules/enketo-core/src/js/plugins.js:3:9)
    at Object.<anonymous> ([project_path]/node_modules/enketo-core/src/js/plugins.js:6:1)

All I've done is spin up a small Node app, added:

var Form = require('enketo-core');

to the top of app.js, and attempted to run $node app.js

running OSX yosemite with node v4.1.2 

Thanks,
Will

**Comment by wpride** [comment]
(being dumb)
